version: "3"
services: 
    nginx:
            build: "./nginx"
            container_name: "nginx"
            ports: 
                    - "80:80"
                    - "443:443"
            restart: "always"

    my-react-app:
            build: "./"
            ports: 
                    - "3000:3000"